title: "Aleksandra's portfolio"
description: "A collection of technical writing samples and a tech-related article showcasing my writing style."
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme